### ISSUE TITLE
Error: Cannot locate the .lib files for the following libraries: duckdb

### ISSUE THREAD

**Issue by lost22git** [amauryt/crystal-duckdb#1]
Hi, I'm using the shard and duckdb for the first time on Windows and getting the error: 

Error: Cannot locate the .lib files for the following libraries: duckdb

thanks 

* `crystal env`

```shell
CRYSTAL_VERSION=1.12.1
CRYSTAL_LIBRARY_PATH=libduckdb-windows-amd64;E:\scoop\global\apps\crystal\current\lib
CRYSTAL_LIBRARY_RPATH=libduckdb-windows-amd64
CRYSTAL_OPTS=""
```

**Comment by michaeldesu** [comment]
I also faced this issue, and was initially glad to see another had posted. However it's not so helpful to have closed this issue without outlining the solution.

After digging around & trial and error, I believe the solution is:

- download a lib package (libduckdb-windows-amd64.zip  or libduckdb-windows-arm64.zip) from DuckDB's [releases page](https://github.com/duckdb/duckdb/releases/)
- unzip and put the .lib file into the CRYSTAL_LIBRARY_PATH
- put the .dll file into the same folder as you exe

I think this info should be put into the README section for visibility.

**Comment by amauryt** [comment]
Hi @michaeldesu. As I mentioned on #2, I don't have access to a machine with Windows, so I'm not familiar with how to develop for it. Also, as already stated in the README: "You must have a compatible DuckDB engine installed and available as a dynamic library within your app."

Given that there are many variations on how to achieve this —including your proposed solution— I only suggest the one I'm familiar with (`brew`).
